### PR TITLE
Make main window transparent for reference work.

### PR DESCRIPTION
**Pull request by jeremybullock**
This creates a new option in the view menu to make the main window semi-transparent.  This is to make using references easier (or for watching YouTube while you animate.)

transparent

### CODE REVIEW

**Comment by jeremybullock** [comment]
I added a slider to control the amount:
slider

**Comment by artisteacher** [comment]
This works really well on macOS. It'll definitely be helpful.

**Comment by jeremybullock** [comment]
Glad to hear it works on Mac.  I was hoping, but couldn't test.

**Comment by adamearle** [comment]
Fantastic mate. Brilliant. Its little things like this that can really speed your day along.

**Pull request merged**
