### PR TITLE
Fix Mac Crash on Close

### LINKED ISSUE #141: Crash on close in macOS
**Describe the bug**
Sometimes closing Tahoma from the 2D room causes a crash. When this happens, it resets any size adjustments to the windows in the 2D room back to the default. A crash notification doesn't come up, but there's a crash report visible in Console. If this happens once, it happens every time closing from the 2D room.

**To Reproduce**
List steps to reproduce the behavior.
1. Close Tahoma with the 2D room open (closing method makes no difference)

**Screenshots**
Screen Shot 2020-09-05 at 12 04 49 PM

It looks like this might be the problem:
Screen Shot 2020-09-05 at 12 09 09 PM

**Device Information:**
 - OS: [macOS 10.14.6 & 10.15.6]
 - Tahoma Version: [1.0.1]

### PR DESCRIPTION
**Pull request by jeremybullock**
Closes #141 Hopefully.

Adds a destructor to Orientation and derived classes.

### CODE REVIEW

**Comment by jeremybullock** [comment]
@artisteacher When you get the chance, would you mind testing this out?

**Comment by jeremybullock** [comment]
Do you know when this started happening?  If you add another panel to the 2D room, close and restart, does it stick around?

#135 shouldn't have affected things that way, but I can make it Windows only if it seems to.

**Comment by jeremybullock** [comment]
If you want to try commenting out lines 524-527 and 552-557 in docklayout.cpp, that would check to see if #135 was the issue.

**Comment by artisteacher** [comment]
Commenting out those lines does stop the timeline from shrinking upon reopening. The stop motion controls & the style editor do still get narrower. The stop motion controls are barely visible, so that's the worst. The style editor & palette shrink a little, but not nearly as much:

Adjusted width size:
Screen Shot 2020-09-11 at 5 15 23 PM

Width after reopening:
Screen Shot 2020-09-11 at 5 15 11 PM

**Comment by jeremybullock** [comment]
Do you want me to make all the fixed size panels be windows only?

**Comment by artisteacher** [comment]
What do you mean by windows only?

**Comment by artisteacher** [comment]
Oh, do you mean the OS? I like that the fixed windows stay the same size when resizing the window. It's preferable to the old behavior where they stretched out disproportionally. 

It's just strange how they resize in the active room upon reopening. Ie. if I make make the stop motion controls window wider and then close Tahoma from the 2D room, the stop motion controls window stays the same when I switch back to the stop motion room after opening. However, if I close from the stop motion room instead of the 2D room, the stop motion controls are practically hidden upon reopening. The active room on close/open shouldn't change the window size.

**Comment by jeremybullock** [comment]
@artisteacher I'm a little confused too.  Did it do that in the first Mac beta you made?

Ok if I merge this to at least solve the crash on close?

**Comment by artisteacher** [comment]
> Did it do that in the first Mac beta you made?

I think so - that's likely why the size of the windows seemed so off #112.

Sure, it's fine to merge this for the crash & deal with the resizing glitch in a new PR. That issue definitely doesn't happen on OT. Could it relate to #59?

**Pull request merged**
