### PR TITLE
Add Save Scene warning popup

### PR DESCRIPTION
**Pull request by manongjohn**
This PR adds a Save Scene warning popup, primarily for new users who may try to use Save Scene and not understand its impact.

image

The popup can be disabled by checking `Do not show again` option.  It can be disabled/re-enabled in `Preferences -> Saving` as well.

Feel free to suggest a better message.

### CODE REVIEW

**Comment by artisteacher** [comment]
It would be good to simplify a little. What about:
"This only saves scene data, not unsaved level changes."

**Comment by manongjohn** [comment]
Should I keep the question? Shorten it? Maybe keep just your message and change the buttons to `OK` and `Save All Instead`?

**Comment by turtletooth** [comment]
I’d keep the question.

**Comment by artisteacher** [comment]
If you want to shorten the question, what about this:
"Did you want to save only the scene, or save all?"

**Comment by turtletooth** [comment]
Great!

**Pull request merged**
