### PR TITLE
Tahoma build scripts

### PR DESCRIPTION
**Pull request by manongjohn**
This PR adds a script to build Tahoma on macOS and linux environments.

These scripts are not intended for building PRs through Travis as the artifacts are not able to be added to the PR. They can be used for master Travis builds without Canon support. The master build artifacts can be added to a nightlies page at a later date.

These were made for macOS 10.13 (High Sierra) and Ubuntu 16.04 (Xenial).

Building steps (replace `env` with `osx` or `linux`):
1. Go to root of Tahoma repository

2. Run install script 1x to download and install precompiled packages (brew on macOS, apt-get on Ubuntu)
```
$ ci-scripts/env/tahoma-install.sh
```

3. Run ffmpeg build script 1x to download ffmpeg source and compile options for LGPL license
```
$ ci-scripts/env/tahoma-buildffmpeg.sh
```
NOTE:
   - Linux build also includes downloading and compiling openH264. openH264is brew'd in for macOS builds.
   - Downloaded source found and compiled in `thirdparty/openh264` (linux only) and `thirdparty/ffmpeg`.

4. Run opencv build script 1x to download opencv source and compile
```
$ ci-scripts/env/tahoma-buildopencv.sh
```
NOTE:
   - Downloaded source found and compiled in `thirdparty/opencv`.

5. Run Tahoma build script as needed
```
$ ci-scripts/env/tahoma-build.sh
```
NOTE:
   - If `thirdparty/canon/Header` directory is detected, it will automatically build with WITH_CANON flag

6. Run packaging script to build Tahoma.app (in Tahoma-osx.dmg) for macOS/Tahoma.AppImage (in Tahoma-linux.tar.gz) for linux
```
$ ci-scripts/env/tahoma-buildpkg.sh
```
NOTE: 
   - If `thirdparty/ffmpeg/bin` directory is detected, it will package the binaries with the release.
   - The compiled ffmpeg binaries from step 3 are not used for packaging, yet, because I need to work on building stand alone ffmpeg binaries.  The compiled version expects certain shared libraries are already installed so may not work on other machines.

### CODE REVIEW

**Comment by artisteacher** [comment]
If building with Xcode for release, line 3 needs to be:
`export TOONZDIR=toonz/build/toonz/release/`

Copying Canon will only work if line 20 is changed to:
 `cp -R thirdparty/canon/Framework/ $TOONZDIR/Tahoma.app/Contents/Frameworks`
Otherwise the framework contents don't actually get copied.

**Comment by manongjohn** [comment]
Thanks for reviewing.

> If building with Xcode for release, line 3 needs to be:
> `export TOONZDIR=toonz/build/toonz/release/`

This script assumes you are building command line using the `travis-build.sh` which doesn't create release folder.  I will add logic to check for a `release` folder and use that if found.

I also plan on updating this and travis-builds.sh scripts for both macOS and Linux versions to make them rerunable so it won't always try to download stuff if it has already.  This would make it easier for people to build locally by just running the travis-* scripts, which is what I do.

**Comment by manongjohn** [comment]
Hmm. Small problem.  I just found this notice on the ffmpeg.zeranoe.com site.

```
ffmpeg.zeranoe.com will close on Sep 18, 2020, and all builds will be removed. If you're using Zeranoe FFmpeg Builds in your product, please ensure that you have a hosting strategy in place by the 18th. Thank you to everyone who supported the project along the way!
```

Need to find another way to source ffmpeg/ffprobe for automated builds if we can.  Otherwise, I'll need to modify the scripts to skip packaging ffmpeg.

**Comment by artisteacher** [comment]
That's too bad. If you don't find another source, maybe you should add logic to include ffmpeg only if the directory exists.

**Comment by manongjohn** [comment]
ffmpeg.org lists evermeetcx/ffmpeg as another source for static builds.  I can use that but would probably need to add another license for that since the source is now different from the Windows builds.

Does ffmpeg.zeranoe.com shutting down impact the ffmpeg binaries packaged with Windows builds in any way? 

ffmpeg.org doesn't list any other places to get Windows binaries at this time.  Not sure what that means going forward for Windows Users in the general OT community as that was the main place to get it.

Should we look at compiling our own binaries and including it in `thirdparty` with appropriate license, somehow?

**Comment by manongjohn** [comment]
Doesn't appear I'll be able to use evermeetcx's version.

What path should I look for ffmpeg to know I can include it?

**Comment by turtletooth** [comment]
We don't need the latest builds.  We just need a LGPL build with OpenH264 included.  Perhaps there is a zeranoe repo we could clone and then post a release to.  We don't need to keep current with FFmpeg, at least in the short term.

**Comment by jeremybullock** [comment]
@manongjohn Feel free to merge any commits that need to be made for travis or appveyor.  No need to wait for a PR to be checked once it's ready.  You know more about those systems than I do.

**Comment by jeremybullock** [comment]
@manongjohn Is this ready to be merged, or should I hold off?

**Comment by manongjohn** [comment]
Please hold off. I just marked it WIP.

I finally got my macOS scripts building lgpl ffmpeg & opencv with lgpl ffmeg from source as dependencies for building OTX releases and plan on releasing similar scripts for Tahoma.

**Comment by jeremybullock** [comment]
Thanks for your work on this @manongjohn 
I noticed the WIP is gone.  Is this ready to go?

**Comment by manongjohn** [comment]
Yes it can go.  Only thing I would suggest is to look at the build parameters for ffmpeg and opencv to make sure I didn't omit something needed/expected by Tahoma or include something I shouldn't have.  They are slightly different for macOS and Linux.  I did make sure to build with openH264 as mentioned previously.

These scripts build shared libraries for ffmpeg as it's needed to compile opencv.  For including ffmpeg in packages, static ffmpeg needs to be compiled, separately.  I've done this locally for the Linux builds since I'll be providing those.

The scripts themselves are not being used by any processes, yet, so those can go in without any real issue. I only made 1 code change to allow Linux builds to detect the ffmpeg packaged within the Tahoma build folder, similar to how macOS detects ffmpeg.

**Comment by jeremybullock** [comment]
Awesome. I’ll take a look.  There has been steady interest in a Linux build.

**Comment by jeremybullock** [comment]
Man! Looks like you put a lot of work into this.  Thank you so much.

**Comment by jeremybullock** [comment]
You are a build script wizard.  I gave the scripts a look, and they seem fine.  (But my knowledge of these things is limited.)  Thanks again.

**Comment by artisteacher** [comment]
Using the opencv build script on macOS works just fine until the very end:
Screen Shot 2020-09-23 at 6 54 12 PM

**Comment by manongjohn** [comment]
Did you `brew remove opencv` or remove any previous opencv installation?

**Comment by artisteacher** [comment]
I've done that previously & just removed the version I was using from Jeremy. Doing a search of usr/local, it looks like there's an opencv directory inside of boost & inside of cmake itself. Could that be problematic? 

Running again, I get this:
Screen Shot 2020-09-23 at 7 26 28 PM

**Comment by artisteacher** [comment]
Just ran the script again with sudo & it succeeded.

**Comment by manongjohn** [comment]
I think I had that problem even after i brew removed opencv that i was originally building with.

Check the permission and ownership on the /usr/local/share/licenses/opencv4.  More than likely owner write permissions was taken away by whatever originally created and didnt remove it when uninstalled. I would force delete that opencv4 folder.

**Comment by manongjohn** [comment]
I can update the script to do a `sudo make install` to ensure that doesn't happen again.

**Comment by artisteacher** [comment]
Perfect. I'll check the other scripts on macOS & let you know if there are any other issues.

On a related topic, do you think exporting the minimum deployment target before running make might have any difference in backwards compatibility?

**Comment by artisteacher** [comment]
4 errors running tahoma-install.sh:
Screen Shot 2020-09-23 at 8 05 31 PM

**Comment by manongjohn** [comment]
For building Tahoma, I actually tried to set the CMAKE_OSX_DEPLOYMENT_TARGET=10.9 in the script but it failed to compile for some reason. I set it aside and never got back to it.

**Comment by manongjohn** [comment]
The Tcr errors in the tahoma-install.sh script actually also happens in the travis version used by OTX and OT. I should remove it. I don't think it is needed anymore.

**Comment by artisteacher** [comment]
The ffmpeg script runs into a permissions issue on installing too.

**Comment by artisteacher** [comment]
The tahoma-buildpkg.sh script fails to copy ffmpeg. Looking in the thirdparty ffmpeg directory, you can see no bin directory is created on macOS when running the ffmpeg script.
Screen Shot 2020-09-23 at 9 34 05 PM

**Comment by manongjohn** [comment]
The ffmpeg/bin is something you would create yourself and you have to put  static built version of ffmpeg in there. You can either build separately or use a one from a download from another site.   For macOS, you can use the version Jeremy provided in the private repo.

The version built by tahoma-buildffmpeg.sh is meant only for building opencv, not for sharing since it isn't built as a static executable.  Some modifications are required to the build script to make it a static version you can include in the release.  I do have a separate script for building statically that I used for the Linux build.  I can adopt it to macOS and include that as well,

**Comment by artisteacher** [comment]
I am getting warnings when building that opencv & various libraries were built for a higher macOS version than is being linked. Could the minimum deployment target need to be exported in any of the other scripts too?

**Comment by manongjohn** [comment]
I can certainly add it.

**Pull request merged**
